### ISSUE TITLE
Support thin Archive

### ISSUE THREAD

**Issue by crazyhouse33** [viraptor/arpy#14]
Hey. Just wanted to notify you that I wanted to use your parser but I cant because it does no support thin archives:

Archive creation:
```
/usr/bin/ar qc libext_lib_normal.a -T CMakeFiles/ext_lib_normal.dir/ext_lib.c.o
/usr/bin/ranlib libext_lib_normal.a
```

arpy:
```
ar = arpy.Archive('libext_lib_normal.a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/arpy.py", line 203, in __init__
    raise ArchiveFormatError("file is missing the global header")
arpy.ArchiveFormatError: file is missing the global header

```

**Comment by crazyhouse33** [comment]
I wont do a pull request yet, because I am not sure it works (I don't know anything about ar format, and don't know what tricky stuff to test to check to integrate it properly in your API). But I can get the information I want by changing line 220 to:
`if self._read(GLOBAL_HEADER_LEN) not in [ b"!<arch>\n",b"!<thin>\n"]:`

Then I am able to list the content of the archive, which is the only feature I care about:
```
ar = arpy.Archive('/opt/personnal_stuff/auto-CMake/build/rings/code/extern/lib/an_extern_lib/libext_lib_normal.a')
ar.read_all_headers()
files=ar.archived_files.keys()
print (files)

dict_keys([b'CMakeFiles/ext_lib_normal.dir/ext_lib.c.o'])
```
